In [1]:
print(5)

5


In [2]:
print(2+3)

5


In [3]:
print(2*3)

6


In [4]:
print(4/2)

2.0


In [5]:
print(4-3)

1


In [6]:
print(2**3)

8


In [7]:
print("hello world")

hello world


In [8]:
print(5+3)

8


In [9]:
print(5*3)

15


In [10]:
print("hello world 2")

hello world 2


In [11]:
print(5* "hello world\n")

hello world
hello world
hello world
hello world
hello world



In [12]:
print(2+3+4)

9


In [13]:
print(2*5)

10


In [14]:
print(3*4+2)

14


In [15]:
print(30/5)

6.0


In [16]:
print(4**2)

16


In [17]:
print("Good afternoon")

Good afternoon


In [18]:
import numpy as np

In [19]:
a = np.arange(1, 10, 2)

In [20]:
print(a)

[1 3 5 7 9]


In [21]:
a = np.arange(1, 10, 3)

In [22]:
print(a)

[1 4 7]


In [23]:
a = np.logspace(1, 4 ,4, base=2)

In [24]:
print(a)

[  2.   4.   8.  16.]
